let g:Imap_PlaceHolderStart = '«'
let g:Imap_PlaceHolderEnd   = '»'
let g:Tex_DefaultTargetFormat = 'pdf'
let g:Tex_MultipleCompileFormats = 'dvi,pdf'
let g:Text_GotoError = 0
let g:Tex_ViewRuleComplete_pdf = 'evince $*.pdf >/dev/null 2>&1 &'
let g:Tex_ViewRuleComplete_dvi = 'evince $*.dvi >/dev/null 2>&1 &'
let g:Tex_ViewRuleComplete_ps  = 'evince $*.ps  >/dev/null 2>&1 &'
setlocal iskeyword+=:
