#!/bin/bash

# Keyboard setup
# US-Intl. AltGr layout, Caps is Ctrl, Menu is Compose
try_start setxkbmap -layout us -variant altgr-intl -option caps:backspace -option compose:menu
# Make useless <> key useful
try_start xmodmap -e "keycode 94 = Super_L Super_L Super_L"
try_start xmodmap -e "add mod4 = Super_L"
# Fix stupid xlock killer anti-feature
try_start xmodmap -e "keycode 63 = KP_Multiply NoSymbol KP_Multiply NoSymbol"
try_start xmodmap -e "keycode 106 = KP_Divide NoSymbol KP_Divide NoSymbol"

# Other X settings
try_start xset b off
try_start xset +dpms dpms 300 600 900
try_start xset r rate 200 40
try_start xset s off

# Fix gdm enabling accessibilty features
try_start xkbset -a

# Wallpapers
systemctl --user start wallpaper

# Hide mouse cursor
try_start_bg unclutter

# Screensaver/locker
try_start_bg xss-lock -- i3lock -n

# Media automounting
try_start_bg udiskie --tray

# Wifi
try_start_bg nm-applet

# Volume control
try_start_bg volumeicon

try_start_bg_delay 2 ssh-add ~/.ssh/id_rsa </dev/null

# OwnCloud
try_start_bg_delay 10 owncloud
