#!/bin/bash

# ConsoleKit
if [ -x /usr/bin/ck-launch-session ]; then
    PREPEND="$PREPEND /usr/bin/ck-launch-session"
fi

# GPG/SSH agent
if [ -z "$SSH_AUTH_SOCK" ] && [ -x /usr/bin/ssh-agent ]; then
    PREPEND="$PREPEND ssh-agent"
fi

# DBus
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ] && [ -x /usr/bin/dbus-launch ]; then
    PREPEND="$PREPEND dbus-launch --exit-with-session"
fi

# If we have to prepend something, restart
if [ -z "$XSESSION_RESTARTED" ]; then
    export XSESSION_RESTARTED=1
    if shopt -q login_shell; then
        exec $PREPEND bash $0 "$@"
    else
        exec $PREPEND bash -l $0 "$@"
    fi
fi

# X resources
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# Keyboard setup
# US-Intl. AltGr layout, Caps is Ctrl, Menu is Compose
setxkbmap -layout us -variant altgr-intl -option ctrl:nocaps -option compose:menu
# Make useless <> key useful
xmodmap -e "keycode 94 = Super_L Super_L Super_L"
xmodmap -e "add mod4 = Super_L"
# Fix stupid xlock killer anti-feature
xmodmap -e "keycode 63 = KP_Multiply NoSymbol KP_Multiply NoSymbol"
xmodmap -e "keycode 106 = KP_Divide NoSymbol KP_Divide NoSymbol"

# Other X settings
xset b off
xset dpms 300 600 900
xset r rate 200 40
xset s off
if [[ -n $LAPTOP ]]; then
    xset m 2 0
else
    xset m 1 0
fi

# Add SSH key
if [ -n "$SSH_AUTH_SOCK" ] && [ -e ~/.ssh/id_rsa ]; then
    [ -z "$SSH_ASKPASS" ] && [ -x /usr/lib/openssh/ssh-askpass ] && export SSH_ASKPASS=/usr/lib/openssh/ssh-askpass
    [ -n "$SSH_ASKPASS" ] && (sleep 1 && ssh-add ~/.ssh/id_rsa < /dev/null) &
fi

# Hide mouse cursor
[ -x /usr/bin/unclutter ]                   && /usr/bin/unclutter &

# Media automounting
[ -x /usr/bin/udiskie ]                     && /usr/bin/udiskie &
[ -x /usr/bin/mount-tray ]                  && /usr/bin/mount-tray &

# Wifi
[ -x /usr/bin/wicd-gtk ]                    && /usr/bin/wicd-gtk &

# Battery
[ -x /usr/bin/batti ]                       && /usr/bin/batti &

# Other applications
[ -x /usr/bin/gstm ]                        && (sleep 2 && /usr/bin/gstm) &
[ -x /usr/bin/SpiderOak ]                   && (sleep 2 && /usr/bin/SpiderOak) &

# Window manager
[ -x /usr/bin/i3 ]                          && exec i3

# Window manager
[ -x /usr/bin/awesome ]                     && exec awesome

# Fallback to xterm
[ -x /usr/bin/xterm ]                       && exec xterm
